feat: support load and save hnsw
jina-ai/annlite pull request #133
Opened 2022-07-28 05:35 UTC by jemmyshin

This pr related to this [issue](https://github.com/jina-ai/annlite/issues/132).

Implemented two APIs inside HNSW: `load_index()` and `save_index()`. In this way we can load the HNSW faster than rebuilding the whole graph

2022-07-28 06:56 UTC, JoanFM requested changes
Need tests

2022-07-28 06:56 UTC, JoanFM commented on annlite/core/index/hnsw/index.py
> +        path_to_load: Optional[str] = None,
can u put it at the end so that is less of a breaking change?

2022-07-29 02:15 UTC, numb3r3 requested changes

2022-07-29 02:15 UTC, numb3r3 commented on annlite/core/index/hnsw/index.py
> +    def _load_index(self):
```suggestion
    def load_index(self, index_file: Union[str, Path]):
```

2022-07-29 02:15 UTC, numb3r3 commented on annlite/core/index/hnsw/index.py
> +        path_to_load: Optional[str] = None,
```suggestion
        index_file: Optional[Union[str, Path]] = None,
```

2022-07-29 02:15 UTC, numb3r3 commented on annlite/core/index/hnsw/index.py
> +        :param path_to_load: The path of saved index, will load the indexer from it when provided
```suggestion
        :param index_file: A file-like object or a string containing a file name. 
```

2022-07-29 02:15 UTC, numb3r3 commented on annlite/core/index/hnsw/index.py
> +    def save_index(self, path):
```suggestion
    def save_index(self, index_file: Union[str, Path]):
```

2022-07-29 02:15 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +    return hnsw
yield hnsw

2022-07-29 02:15 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +    hnsw.save_index(os.path.join(tmpdir, 'hnsw.pkl'))
```suggestion
    build_hnsw.save_index(os.path.join(tmpdir, 'hnsw.pkl'))
```

2022-07-29 02:15 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +    hnsw_wrong = HnswIndex(dim=512, path_to_load=os.path.join(tmpdir, 'hnsw_wrong.pkl'))
raise an exception if the given index file does not exist.

2022-07-29 02:15 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +    hnsw.save_index(os.path.join(tmpdir, 'hnsw.pkl'))
same

2022-07-29 07:51 UTC, numb3r3 requested changes

2022-07-29 07:51 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +n_examples = 2000
use small num to speedup test

2022-07-29 07:51 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +    hnsw = HnswIndex(dim=512)
```suggestion
    hnsw = HnswIndex(dim=n_features)
```

2022-07-29 07:51 UTC, numb3r3 commented on tests/test_hnsw_load_save.py
> +def test_load(tmpdir, build_hnsw):
can be combined into one test case

2022-07-29 08:15 UTC, numb3r3 approved these changes
LGTM

2022-07-29 08:16 UTC, merged