feat: integrate annlite with projector
jina-ai/annlite pull request #136
Opened 2022-08-03 06:37 UTC by jemmyshin

This pr related to this [issue](https://github.com/jina-ai/annlite/issues/134)

Implement projector with `annlite`.

2022-08-03 06:50 UTC, numb3r3 requested changes

2022-08-03 06:50 UTC, numb3r3 commented on annlite/core/codec/projector.py
> +        self.dim = dim
add `assert dim > n_components`

2022-08-03 06:50 UTC, numb3r3 commented on annlite/core/codec/projector.py
> +        assert x.shape[1] == self.dim, 'dimension of input data must be equal to "dim"'
```suggestion
        assert x.shape == (2, self.dim), 'dimension of input data must be equal to "dim"'
```

2022-08-03 07:19 UTC, jemmyshin commented on annlite/core/codec/projector.py
> +        assert x.shape[1] == self.dim, 'dimension of input data must be equal to "dim"'
why `x.shape[0] == 2` ?

2022-08-03 07:20 UTC, numb3r3 commented on annlite/core/codec/projector.py
> +        assert x.shape[1] == self.dim, 'dimension of input data must be equal to "dim"'
oh, my fault.

2022-08-03 09:04 UTC, numb3r3 requested changes

2022-08-03 09:04 UTC, numb3r3 commented on annlite/index.py
> +            n_components=n_components,
we can get the `n_components` from self.project_codec

2022-08-03 09:47 UTC, numb3r3 requested changes

2022-08-03 09:47 UTC, numb3r3 commented on annlite/container.py
> +        self.n_components = n_components
```suggestion
        self.n_components = self.projector_codec.n_component if self.projector_codec else 0
```

2022-08-03 09:47 UTC, numb3r3 commented on annlite/container.py
> +        n_components: Optional[int] = None,
don't need pass `n_components` parameter in container __init__

2022-08-04 06:03 UTC, numb3r3 approved these changes

2022-08-04 06:03 UTC, merged