fix(cpp): update hnswlib
jina-ai/annlite pull request #185
Opened 2022-10-11 11:34 UTC by OrangeSodahub

2022-10-11 12:37 UTC, JoanFM requested changes

2022-10-11 12:37 UTC, JoanFM commented on include/hnswlib/bruteforce.h
> +            output.close();
u need to cover with `try` and `catch` errors, or u may have an open stream in bad shape

2022-10-11 12:37 UTC, JoanFM commented on include/hnswlib/bruteforce.h
> +            input.close();
make sure to handle exceptions to close properly

2022-10-11 14:10 UTC, OrangeSodahub commented
In `space_ip.h` and `space_l2.h`, some new functions added. I add the parameters like `const local_state_t *local_state` like other functions to make the parameter lists non-conflicting.

2022-10-12 01:07 UTC, OrangeSodahub commented on include/hnswlib/space_ip.h
> +    }
In `space_ip.h` and `space_l2.h`, some new functions added. I add the parameters like `const local_state_t *local_state` to these new functioins like others to make the parameter lists non-conflicting.

2022-10-12 08:36 UTC, numb3r3 commented on include/hnswlib/bruteforce.h
> +            free(data_);
`bruteforce.h` is never used in annlite now, and will not forever. This file is just a copy from hnswlib.

2022-10-13 04:58 UTC, numb3r3 commented
@OrangeSodahub FYI, this PR looks good to me. But I would like to hold it until https://github.com/jina-ai/annlite/pull/186 is merged. This PR is a good example to test the wheel building.

2023-02-28 06:27 UTC, merged