feat: add flag for close
jina-ai/annlite pull request #191
Opened 2022-10-14 08:20 UTC by jemmyshin

We add a flag for denoting whether `Annlite` has been closed already to avoid closing it twice.

2022-10-14 08:21 UTC, numb3r3 requested changes

2022-10-14 08:29 UTC, numb3r3 commented on annlite/storage/kv.py
> +        if self._is_closed:
revert the changes here

2022-10-14 08:59 UTC, numb3r3 approved these changes

2022-10-14 09:44 UTC, JoanFM commented
not a big fan of adding such a flag? why is this needed?

2022-10-17 07:44 UTC, numb3r3 requested changes
@jemmyshin add unittest

2022-10-17 07:49 UTC, numb3r3 commented
@JoanFM In the current docarray, one instance of annlite would be closed (i.e., close rocksdb session) two times some times. Rocksdb does not allow closing a closed session. Hence, in annlite, we use a flag to overcome this problem.

2022-10-17 07:49 UTC, numb3r3 requested changes

2022-10-17 07:49 UTC, numb3r3 commented on annlite/storage/kv.py
> +            warnings.warn(
no warning, just pass

2022-10-17 07:53 UTC, JoanFM commented
> @JoanFM In the current docarray, one instance of annlite would be closed (i.e., close rocksdb session) two times some times. Rocksdb does not allow closing a closed session. Hence, in annlite, we use a flag to overcome this problem.

Isn't there an API from rocksdb to check if session has been closed?

2022-10-17 10:19 UTC, numb3r3 commented
no such API from rocksdb

2022-10-18 05:13 UTC, merged